#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Maths.Resource", IsApplication=true)]

namespace Maths
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int buttonAddiction2 = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int buttonCombinedBasic2 = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int buttonDivision2 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int buttonMIX = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int buttonMultiplication2 = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int buttonSubtraction2 = 2131034115;
			
<<<<<<< HEAD
			// aapt resource value: 0x7f05000f
			public const int button_View_BaseMaths_Next = 2131034127;
=======
			// aapt resource value: 0x7f05000c
			public const int button_View_BaseMaths_Next = 2131034124;
>>>>>>> 33e7c9226e63f9eebdd43e0e9b993f95aa64ea4f
			
			// aapt resource value: 0x7f050001
			public const int buttonexit = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int buttoninfo = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int buttonlearn = 2131034119;
<<<<<<< HEAD
			
			// aapt resource value: 0x7f050008
			public const int buttonstatistics = 2131034120;
			
			// aapt resource value: 0x7f05000e
			public const int edittext_View_BaseMaths = 2131034126;
			
			// aapt resource value: 0x7f05000a
			public const int relativeLayout1 = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int switch1 = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int textView1 = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int textview_View_BaseMahs = 2131034125;
=======
			
			// aapt resource value: 0x7f050008
			public const int buttonstatistics = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int edittext_View_BaseMaths = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int textview_View_BaseMahs = 2131034122;
>>>>>>> 33e7c9226e63f9eebdd43e0e9b993f95aa64ea4f
			
			// aapt resource value: 0x7f050000
			public const int textviewinfo = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Aboutinfo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Learn = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Settings_CombinedMaths = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Stats = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int View_BaseMaths = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
